# Winning Jeopardy

**What the project is about:** Imagine that you want to compete on Jeopardy (a popular TV show in the US where participants answer questions to win money), and you're looking for any way to win. 

**Goal of the project:** In this project, I'll be working with a [dataset of Jeopardy questions](https://www.reddit.com/r/datasets/comments/1uyd0t/200000_jeopardy_questions_in_a_json_file) to figure out some patterns in the questions that could help you win.

## Jeopardy Questions

In [1]:
import pandas
import csv

jeopardy = pandas.read_csv("jeopardy.csv")

jeopardy

,Show Number,Air Date,Round,Category,Value,Question,Answer
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams
5,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$200,"In the title of an Aesop fable, this insect sh...",the ant
6,4680,2004-12-31,Jeopardy!,HISTORY,$400,Built in 312 B.C. to link Rome & the South of ...,the Appian Way
7,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$400,"No. 8: 30 steals for the Birmingham Barons; 2,...",Michael Jordan
8,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$400,"In the winter of 1971-72, a record 1,122 inche...",Washington
9,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$400,This housewares store was named for the packag...,Crate & Barrel
10,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$400,"""And away we go""",Jackie Gleason
11,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$400,Cows regurgitate this from the first stomach t...,the cud
12,4680,2004-12-31,Jeopardy!,HISTORY,$600,In 1000 Rajaraja I of the Cholas battled to ta...,Ceylon (or Sri Lanka)
13,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$600,"No. 1: Lettered in hoops, football & lacrosse ...",Jim Brown
14,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$600,"On June 28, 1994 the nat'l weather service beg...",the UV index
15,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$600,"This company's Accutron watch, introduced in 1...",Bulova
16,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$600,"Outlaw: ""Murdered by a traitor and a coward wh...",Jesse James
17,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$600,"A small demon, or a mischievous child (who mig...",imp
18,4680,2004-12-31,Jeopardy!,HISTORY,$800,Karl led the first of these Marxist organizati...,the International
19,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$800,No. 10: FB/LB for Columbia U. in the 1920s; MV...,(Lou) Gehrig
20,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$800,Africa's lowest temperature was 11 degrees bel...,Morocco
21,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$800,Edward Teller & this man partnered in 1898 to ...,(Paul) Bonwit
22,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,"$2,000","1939 Oscar winner: ""...you are a credit to you...",Hattie McDaniel (for her role in Gone with the...
23,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$800,"In geologic time one of these, shorter than an...",era
24,4680,2004-12-31,Jeopardy!,HISTORY,$1000,This Asian political party was founded in 1885...,the Congress Party
25,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$1000,No. 5: Only center to lead the NBA in assists;...,(Wilt) Chamberlain
26,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$1000,"The Kirschner brothers, Don & Bill, named this...",K2
27,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$1000,"Revolutionary War hero: ""His spirit is in Verm...",Ethan Allen
28,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$1000,"A single layer of paper, or to perform one's c...",ply
29,4680,2004-12-31,Double Jeopardy!,DR. SEUSS AT THE MULTIPLEX,$400,"<a href=""http://www.j-archive.com/media/2004-1...",Horton
...,...,...,...,...,...,...,...
19969,5694,2009-05-14,Double Jeopardy!,AMERICAN HISTORY,$1200,In 1960 the last of these locomotives was reti...,steam engines
19970,5694,2009-05-14,Double Jeopardy!,"MIND YOUR SHAKESPEARE ""P""s & ""Q""s",$1200,"Kate: ""if I be waspish, best beware my sting"";...",Petruchio
19971,5694,2009-05-14,Double Jeopardy!,ALMA MATERS,"$1,500",This private college in Northern California bo...,Stanford University
19972,5694,2009-05-14,Double Jeopardy!,ACTRESSES,$1200,"She voiced Princess Pea in ""The Tale of Desper...",Emma Watson
19973,5694,2009-05-14,Double Jeopardy!,2-LETTER WORDS,$1200,It's the name of the long-awaited new White Ho...,Bo
19974,5694,2009-05-14,Double Jeopardy!,ANGELS & DEMONS,$1200,"Langdon in ""Angels & Demons"" is looking for <a...",an antimatter bomb
19975,5694,2009-05-14,Double Jeopardy!,AMERICAN HISTORY,$1600,In the 1600s most of New York State was occupi...,the Iroquois
19976,5694,2009-05-14,Double Jeopardy!,"MIND YOUR SHAKESPEARE ""P""s & ""Q""s",$1600,Marina's dad (need a hint? he rules Tyre),Pericles
19977,5694,2009-05-14,Double Jeopardy!,ALMA MATERS,$1600,Presidential kids are welcome at this New Orle...,Tulane
19978,5694,2009-05-14,Double Jeopardy!,ACTRESSES,$1600,She didn't vamp it up & did a bella job as Em ...,Kristen Stewart
19979,5694,2009-05-14,Double Jeopardy!,2-LETTER WORDS,$1600,Third syllable intoned by the giant who smells...,fo
19980,5694,2009-05-14,Double Jeopardy!,ANGELS & DEMONS,$1600,"Much of ""Angels & Demons"" takes place at one o...",a conclave
19981,5694,2009-05-14,Double Jeopardy!,AMERICAN HISTORY,"$1,200",In 1899 Secretary of State John Hay proclaimed...,open-door policy
19982,5694,2009-05-14,Double Jeopardy!,"MIND YOUR SHAKESPEARE ""P""s & ""Q""s",$2000,"Fruity surname of Peter in ""A Midsummer Night'...",Quince
19983,5694,2009-05-14,Double Jeopardy!,ALMA MATERS,$2000,"Quincy Jones, Kevin Eubanks & Branford Marsali...",Berklee
19984,5694,2009-05-14,Double Jeopardy!,ACTRESSES,$2000,"In 2009 she returned to being ""Fast & Furious""...",Michelle Rodriguez
19985,5694,2009-05-14,Double Jeopardy!,2-LETTER WORDS,$2000,"The book of Genesis says this ancient city ""of...",Ur
19986,5694,2009-05-14,Double Jeopardy!,ANGELS & DEMONS,$2000,"""Habakkuk and the Angel"" is one of a series of...",Bernini
19987,5694,2009-05-14,Final Jeopardy!,SCIENCE TERMS,None,"In medieval England, it meant the smallest uni...",atom
19988,3582,2000-03-14,Jeopardy!,U.S. GEOGRAPHY,$100,This Texas city is the largest in the U.S. to ...,Houston (Lee Brown)
19989,3582,2000-03-14,Jeopardy!,POP MUSIC PAIRINGS,$100,...& the Crickets,Buddy Holly
19990,3582,2000-03-14,Jeopardy!,HISTORIC PEOPLE,$100,In the 990s this son of Erik the Red brought C...,Leif Ericson
19991,3582,2000-03-14,Jeopardy!,1998 QUOTATIONS,$100,"Concerning a failed Windows 98 demonstration, ...",Bill Gates
19992,3582,2000-03-14,Jeopardy!,LLAMA-RAMA,$100,"This llama product is used to make hats, blank...",Wool
19993,3582,2000-03-14,Jeopardy!,DING DONG,$100,In 1967 this company introduced its chocolate-...,Hostess
19994,3582,2000-03-14,Jeopardy!,U.S. GEOGRAPHY,$200,"Of 8, 12 or 18, the number of U.S. states that...",18
19995,3582,2000-03-14,Jeopardy!,POP MUSIC PAIRINGS,$200,...& the New Power Generation,Prince
19996,3582,2000-03-14,Jeopardy!,HISTORIC PEOPLE,$200,In 1589 he was appointed professor of mathemat...,Galileo
19997,3582,2000-03-14,Jeopardy!,1998 QUOTATIONS,$200,"Before the grand jury she said, ""I'm really so...",Monica Lewinsky
19998,3582,2000-03-14,Jeopardy!,LLAMA-RAMA,$200,Llamas are the heftiest South American members...,Camels

In [2]:
jeopardy.columns

Index(['Show Number', ' Air Date', ' Round', ' Category', ' Value',
       ' Question', ' Answer'],
      dtype='object')

In [3]:
jeopardy.columns = ['Show Number', 'Air Date', 'Round', 'Category', 'Value', 'Question', 'Answer']


Before I can start doing analysis on the Jeopardy questions, I need to normalize all of the text columns (the `Question` and `Answer` columns). The idea here is to ensure that I put words in lowercase and remove punctuation so `Don't` and `don't`, for instance, aren't considered to be different words when I compare them.

## Normalizing Text and Columns

In addition to normalizing the text columns, there are also some other columns to normalize.

For instance, the `Value` column should be numeric, to allow me to manipulate it easier. I'll also need to remove the dollar sign from the beginning of each value and convert the column from text to numeric.

In [4]:
import re

def normalize_text(text):
    text = text.lower()
    text = re.sub("[^A-Za-z0-9\s]", "", text)
    text = re.sub("\s+", " ", text)
    return text

def normalize_values(text):
    text = re.sub("[^A-Za-z0-9\s]", "", text)
    try:
        text = int(text)
    except Exception:
        text = 0
    return text

In [5]:
jeopardy["clean_question"] = jeopardy["Question"].apply(normalize_text)
jeopardy["clean_answer"] = jeopardy["Answer"].apply(normalize_text)
jeopardy["clean_value"] = jeopardy["Value"].apply(normalize_values)

In [6]:
jeopardy

,Show Number,Air Date,Round,Category,Value,Question,Answer,clean_question,clean_answer,clean_value
0,4680,2004-12-31,Jeopardy!,HISTORY,$200,"For the last 8 years of his life, Galileo was ...",Copernicus,for the last 8 years of his life galileo was u...,copernicus,200
1,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$200,No. 2: 1912 Olympian; football star at Carlisl...,Jim Thorpe,no 2 1912 olympian football star at carlisle i...,jim thorpe,200
2,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$200,The city of Yuma in this state has a record av...,Arizona,the city of yuma in this state has a record av...,arizona,200
3,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$200,"In 1963, live on ""The Art Linkletter Show"", th...",McDonald's,in 1963 live on the art linkletter show this c...,mcdonalds,200
4,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$200,"Signer of the Dec. of Indep., framer of the Co...",John Adams,signer of the dec of indep framer of the const...,john adams,200
5,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$200,"In the title of an Aesop fable, this insect sh...",the ant,in the title of an aesop fable this insect sha...,the ant,200
6,4680,2004-12-31,Jeopardy!,HISTORY,$400,Built in 312 B.C. to link Rome & the South of ...,the Appian Way,built in 312 bc to link rome the south of ital...,the appian way,400
7,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$400,"No. 8: 30 steals for the Birmingham Barons; 2,...",Michael Jordan,no 8 30 steals for the birmingham barons 2306 ...,michael jordan,400
8,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$400,"In the winter of 1971-72, a record 1,122 inche...",Washington,in the winter of 197172 a record 1122 inches o...,washington,400
9,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$400,This housewares store was named for the packag...,Crate & Barrel,this housewares store was named for the packag...,crate barrel,400
10,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$400,"""And away we go""",Jackie Gleason,and away we go,jackie gleason,400
11,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$400,Cows regurgitate this from the first stomach t...,the cud,cows regurgitate this from the first stomach t...,the cud,400
12,4680,2004-12-31,Jeopardy!,HISTORY,$600,In 1000 Rajaraja I of the Cholas battled to ta...,Ceylon (or Sri Lanka),in 1000 rajaraja i of the cholas battled to ta...,ceylon or sri lanka,600
13,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$600,"No. 1: Lettered in hoops, football & lacrosse ...",Jim Brown,no 1 lettered in hoops football lacrosse at sy...,jim brown,600
14,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$600,"On June 28, 1994 the nat'l weather service beg...",the UV index,on june 28 1994 the natl weather service began...,the uv index,600
15,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$600,"This company's Accutron watch, introduced in 1...",Bulova,this companys accutron watch introduced in 196...,bulova,600
16,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$600,"Outlaw: ""Murdered by a traitor and a coward wh...",Jesse James,outlaw murdered by a traitor and a coward whos...,jesse james,600
17,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$600,"A small demon, or a mischievous child (who mig...",imp,a small demon or a mischievous child who might...,imp,600
18,4680,2004-12-31,Jeopardy!,HISTORY,$800,Karl led the first of these Marxist organizati...,the International,karl led the first of these marxist organizati...,the international,800
19,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$800,No. 10: FB/LB for Columbia U. in the 1920s; MV...,(Lou) Gehrig,no 10 fblb for columbia u in the 1920s mvp for...,lou gehrig,800
20,4680,2004-12-31,Jeopardy!,EVERYBODY TALKS ABOUT IT...,$800,Africa's lowest temperature was 11 degrees bel...,Morocco,africas lowest temperature was 11 degrees belo...,morocco,800
21,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$800,Edward Teller & this man partnered in 1898 to ...,(Paul) Bonwit,edward teller this man partnered in 1898 to se...,paul bonwit,800
22,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,"$2,000","1939 Oscar winner: ""...you are a credit to you...",Hattie McDaniel (for her role in Gone with the...,1939 oscar winner you are a credit to your cra...,hattie mcdaniel for her role in gone with the ...,2000
23,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$800,"In geologic time one of these, shorter than an...",era,in geologic time one of these shorter than an ...,era,800
24,4680,2004-12-31,Jeopardy!,HISTORY,$1000,This Asian political party was founded in 1885...,the Congress Party,this asian political party was founded in 1885...,the congress party,1000
25,4680,2004-12-31,Jeopardy!,ESPN's TOP 10 ALL-TIME ATHLETES,$1000,No. 5: Only center to lead the NBA in assists;...,(Wilt) Chamberlain,no 5 only center to lead the nba in assists tr...,wilt chamberlain,1000
26,4680,2004-12-31,Jeopardy!,THE COMPANY LINE,$1000,"The Kirschner brothers, Don & Bill, named this...",K2,the kirschner brothers don bill named this ski...,k2,1000
27,4680,2004-12-31,Jeopardy!,EPITAPHS & TRIBUTES,$1000,"Revolutionary War hero: ""His spirit is in Verm...",Ethan Allen,revolutionary war hero his spirit is in vermon...,ethan allen,1000
28,4680,2004-12-31,Jeopardy!,3-LETTER WORDS,$1000,"A single layer of paper, or to perform one's c...",ply,a single layer of paper or to perform ones cra...,ply,1000
29,4680,2004-12-31,Double Jeopardy!,DR. SEUSS AT THE MULTIPLEX,$400,"<a href=""http://www.j-archive.com/media/2004-1...",Horton,a hrefhttpwwwjarchivecommedia20041231dj23mp3be...,horton,400
...,...,...,...,...,...,...,...,...,...,...
19969,5694,2009-05-14,Double Jeopardy!,AMERICAN HISTORY,$1200,In 1960 the last of these locomotives was reti...,steam engines,in 1960 the last of these locomotives was reti...,steam engines,1200
19970,5694,2009-05-14,Double Jeopardy!,"MIND YOUR SHAKESPEARE ""P""s & ""Q""s",$1200,"Kate: ""if I be waspish, best beware my sting"";...",Petruchio,kate if i be waspish best beware my sting his ...,petruchio,1200
19971,5694,2009-05-14,Double Jeopardy!,ALMA MATERS,"$1,500",This private college in Northern California bo...,Stanford University,this private college in northern california bo...,stanford university,1500
19972,5694,2009-05-14,Double Jeopardy!,ACTRESSES,$1200,"She voiced Princess Pea in ""The Tale of Desper...",Emma Watson,she voiced princess pea in the tale of despere...,emma watson,1200
19973,5694,2009-05-14,Double Jeopardy!,2-LETTER WORDS,$1200,It's the name of the long-awaited new White Ho...,Bo,its the name of the longawaited new white hous...,bo,1200
19974,5694,2009-05-14,Double Jeopardy!,ANGELS & DEMONS,$1200,"Langdon in ""Angels & Demons"" is looking for <a...",an antimatter bomb,langdon in angels demons is looking for a href...,an antimatter bomb,1200
19975,5694,2009-05-14,Double Jeopardy!,AMERICAN HISTORY,$1600,In the 1600s most of New York State was occupi...,the Iroquois,in the 1600s most of new york state was occupi...,the iroquois,1600
19976,5694,2009-05-14,Double Jeopardy!,"MIND YOUR SHAKESPEARE ""P""s & ""Q""s",$1600,Marina's dad (need a hint? he rules Tyre),Pericles,marinas dad need a hint he rules tyre,pericles,1600
19977,5694,2009-05-14,Double Jeopardy!,ALMA MATERS,$1600,Presidential kids are welcome at this New Orle...,Tulane,presidential kids are welcome at this new orle...,tulane,1600
19978,5694,2009-05-14,Double Jeopardy!,ACTRESSES,$1600,She didn't vamp it up & did a bella job as Em ...,Kristen Stewart,she didnt vamp it up did a bella job as em in ...,kristen stewart,1600
19979,5694,2009-05-14,Double Jeopardy!,2-LETTER WORDS,$1600,Third syllable intoned by the giant who smells...,fo,third syllable intoned by the giant who smells...,fo,1600
19980,5694,2009-05-14,Double Jeopardy!,ANGELS & DEMONS,$1600,"Much of ""Angels & Demons"" takes place at one o...",a conclave,much of angels demons takes place at one of a ...,a conclave,1600
19981,5694,2009-05-14,Double Jeopardy!,AMERICAN HISTORY,"$1,200",In 1899 Secretary of State John Hay proclaimed...,open-door policy,in 1899 secretary of state john hay proclaimed...,opendoor policy,1200
19982,5694,2009-05-14,Double Jeopardy!,"MIND YOUR SHAKESPEARE ""P""s & ""Q""s",$2000,"Fruity surname of Peter in ""A Midsummer Night'...",Quince,fruity surname of peter in a midsummer nights ...,quince,2000
19983,5694,2009-05-14,Double Jeopardy!,ALMA MATERS,$2000,"Quincy Jones, Kevin Eubanks & Branford Marsali...",Berklee,quincy jones kevin eubanks branford marsalis a...,berklee,2000
19984,5694,2009-05-14,Double Jeopardy!,ACTRESSES,$2000,"In 2009 she returned to being ""Fast & Furious""...",Michelle Rodriguez,in 2009 she returned to being fast furious as ...,michelle rodriguez,2000
19985,5694,2009-05-14,Double Jeopardy!,2-LETTER WORDS,$2000,"The book of Genesis says this ancient city ""of...",Ur,the book of genesis says this ancient city of ...,ur,2000
19986,5694,2009-05-14,Double Jeopardy!,ANGELS & DEMONS,$2000,"""Habakkuk and the Angel"" is one of a series of...",Bernini,habakkuk and the angel is one of a series of a...,bernini,2000
19987,5694,2009-05-14,Final Jeopardy!,SCIENCE TERMS,None,"In medieval England, it meant the smallest uni...",atom,in medieval england it meant the smallest unit...,atom,0
19988,3582,2000-03-14,Jeopardy!,U.S. GEOGRAPHY,$100,This Texas city is the largest in the U.S. to ...,Houston (Lee Brown),this texas city is the largest in the us to ha...,houston lee brown,100
19989,3582,2000-03-14,Jeopardy!,POP MUSIC PAIRINGS,$100,...& the Crickets,Buddy Holly,the crickets,buddy holly,100
19990,3582,2000-03-14,Jeopardy!,HISTORIC PEOPLE,$100,In the 990s this son of Erik the Red brought C...,Leif Ericson,in the 990s this son of erik the red brought c...,leif ericson,100
19991,3582,2000-03-14,Jeopardy!,1998 QUOTATIONS,$100,"Concerning a failed Windows 98 demonstration, ...",Bill Gates,concerning a failed windows 98 demonstration h...,bill gates,100
19992,3582,2000-03-14,Jeopardy!,LLAMA-RAMA,$100,"This llama product is used to make hats, blank...",Wool,this llama product is used to make hats blanke...,wool,100
19993,3582,2000-03-14,Jeopardy!,DING DONG,$100,In 1967 this company introduced its chocolate-...,Hostess,in 1967 this company introduced its chocolatec...,hostess,100
19994,3582,2000-03-14,Jeopardy!,U.S. GEOGRAPHY,$200,"Of 8, 12 or 18, the number of U.S. states that...",18,of 8 12 or 18 the number of us states that tou...,18,200
19995,3582,2000-03-14,Jeopardy!,POP MUSIC PAIRINGS,$200,...& the New Power Generation,Prince,the new power generation,prince,200
19996,3582,2000-03-14,Jeopardy!,HISTORIC PEOPLE,$200,In 1589 he was appointed professor of mathemat...,Galileo,in 1589 he was appointed professor of mathemat...,galileo,200
19997,3582,2000-03-14,Jeopardy!,1998 QUOTATIONS,$200,"Before the grand jury she said, ""I'm really so...",Monica Lewinsky,before the grand jury she said im really sorry...,monica lewinsky,200
19998,3582,2000-03-14,Jeopardy!,LLAMA-RAMA,$200,Llamas are the heftiest South American members...,Camels,llamas are the heftiest south american members...,camels,200


The `Air Date` column should also be a datetime, not a string, to enable me to work it easier.

In [7]:
jeopardy["Air Date"] = pandas.to_datetime(jeopardy["Air Date"])

In [8]:
jeopardy.dtypes

Show Number                int64
Air Date          datetime64[ns]
Round                     object
Category                  object
Value                     object
Question                  object
Answer                    object
clean_question            object
clean_answer              object
clean_value                int64
dtype: object

## Answers in Questions

In order to figure out whether to study past questions, study general knowledge, or not study it all, it would be helpful to figure out two things:

- How often the answer can be used for a question
- How often questions are repeated

I can answer the second question by seeing how often complex words (> 6 characters) reoccur. I can answer the first question by seeing how many times words in the answer also occur in the question. For now, I'll work on the first question and come back to the second later.

In [9]:
def count_matches(row):
    split_answer = row["clean_answer"].split()
    split_question = row["clean_question"].split()
    if "the" in split_answer:
        split_answer.remove("the")
    if len(split_answer) == 0:
        return 0
    match_count = 0
    for item in split_answer:
        if item in split_question:
            match_count += 1
    return match_count / len(split_answer)

jeopardy["answer_in_question"] = jeopardy.apply(count_matches, axis=1)

In [10]:
jeopardy["answer_in_question"].mean()

0.05900196524977763

On average, the answer only makes up for about 6% of the question. This isn't a huge number, and means that I can't just hope that hearing a question will enable me to figure out the answer. I'll likely have to study.

## Recycled Questions

Let's say I want to investigate how often new questions are repeats of older ones. I can't completely answer this, because I only have about 10% of the full Jeopardy question dataset, but I can investigate it a little by:

- Sorting `jeopardy` in order of ascending air date
- Maintaining a set called `terms_used` that will be empty initially
- Iterating through each row of `jeopardy`
- Splitting `clean_question` into words, removing any word shorter than 6 characters, and checking whether each word occurs in `terms_used`
    - If it does, increment a counter.
    - Then add each word to `terms_used`

Doing this allows me to check if the terms in questions have been used previously or not. Only looking at words with six or more characters enables me to filter out words like `the` and `than`, which are commonly used, but don't tell me a lot about a question.

In [11]:
question_overlap = []
terms_used = set()

jeopardy = jeopardy.sort_values("Air Date")

for i, row in jeopardy.iterrows():
        split_question = row["clean_question"].split(" ")
        split_question = [q for q in split_question if len(q) > 5]
        match_count = 0
        for word in split_question:
            if word in terms_used:
                match_count += 1
        for word in split_question:
            terms_used.add(word)
        if len(split_question) > 0:
            match_count /= len(split_question)
        question_overlap.append(match_count)
jeopardy["question_overlap"] = question_overlap

jeopardy["question_overlap"].mean()

0.6876260592169802

It looks like there is about 70% overlap between terms in new questions and terms in old questions. However, this only looks at a small set of questions, and it doesn't look at phrases - it looks at single terms. This makes it relatively insignificant, but it does mean that it's worth looking more into the recycling of questions.

## Low Value vs High Value Questions

Let's say I only want to study questions that pertain to high value questions instead of low value questions. This will help me earn more money when I'm on Jeopardy.

I can actually figure out which terms correspond to high-value questions using a chi-squared test. But first, I'll need to narrow down the questions into two categories:

- Low value - Any row where `Value` is less than 800.
- High value - Any row where `Value` is greater than 800.

I'll then be able to loop through each of the terms in the `terms_used` column and:

- Find the number of low value questions the word occurs in
- Find the number of high value questions the word occurs in
- Find the percentage of questions the word occurs in
- Based on the percentage of questions the word occurs in, find expected counts
- Compute the chi squared value based on the expected counts and the observed counts for high and low value questions

I can then find the words with the biggest differences in usage between high and low value questions, by selecting the words with the highest associated chi-squared values. Doing this for all of the words would take a very long time, however, so for now, I'll just do it for a small sample.

In [12]:
def determine_value(row):
    value = 0
    if row["clean_value"] > 800:
        value = 1
    return value

jeopardy["high_value"] = jeopardy.apply(determine_value, axis=1)

In [13]:
def count_usage(term):
    low_count = 0
    high_count = 0
    for i, row in jeopardy.iterrows():
        if term in row["clean_question"].split(" "):
            if row["high_value"] == 1:
                high_count += 1
            else:
                low_count += 1
    return high_count, low_count

In [14]:
from random import choice

terms_used_list = list(terms_used)
comparison_terms = [choice(terms_used_list) for _ in range(10)]

observed_expected = []

for term in comparison_terms:
    observed_expected.append(count_usage(term))

observed_expected

[(0, 1),
 (0, 1),
 (0, 1),
 (0, 1),
 (0, 1),
 (0, 1),
 (0, 1),
 (0, 7),
 (0, 1),
 (0, 2)]

In [15]:
from scipy.stats import chisquare
import numpy as np

high_value_count = jeopardy[jeopardy["high_value"] == 1].shape[0]
low_value_count = jeopardy[jeopardy["high_value"] == 0].shape[0]

chi_squared = []
for obs in observed_expected:
    total = sum(obs)
    total_prop = total / jeopardy.shape[0]
    high_value_exp = total_prop * high_value_count
    low_value_exp = total_prop * low_value_count
    
    observed = np.array([obs[0], obs[1]])
    expected = np.array([high_value_exp, low_value_exp])
    chi_squared.append(chisquare(observed, expected))

chi_squared

[Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469),
 Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469),
 Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469),
 Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469),
 Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469),
 Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469),
 Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469),
 Power_divergenceResult(statistic=2.813739922888188, pvalue=0.09346026076900309),
 Power_divergenceResult(statistic=0.401962846126884, pvalue=0.5260772985705469),
 Power_divergenceResult(statistic=0.803925692253768, pvalue=0.3699222378079571)]

## Chi-Squared Results

None of the terms had a significant difference in usage between high value and low value rows. Additionally, the frequencies were all lower than 5, so the chi-squared test isn't as valid. It would be better to run this test with only terms that have higher frequencies.